/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlantsRouteImport } from './routes/plants'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as WateringLogRouteImport } from './routes/watering-log'
import { Route as PlantIdRouteImport } from './routes/plant.$id'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiUsersMeRouteImport } from './routes/api/users/me'
import { Route as ApiSensorReadingsHistoryPlantIdRouteImport } from './routes/api/sensor-readings/history.$plantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsRoute = PlantsRouteImport.update({
  id: '/plants',
  path: '/plants',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WateringLogRoute = WateringLogRouteImport.update({
  id: '/watering-log',
  path: '/watering-log',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantIdRoute = PlantIdRouteImport.update({
  id: '/plant/$id',
  path: '/plant/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersMeRoute = ApiUsersMeRouteImport.update({
  id: '/api/users/me',
  path: '/api/users/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSensorReadingsHistoryPlantIdRoute =
  ApiSensorReadingsHistoryPlantIdRouteImport.update({
    id: '/api/sensor-readings/history/$plantId',
    path: '/api/sensor-readings/history/$plantId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/plants': typeof PlantsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/watering-log': typeof WateringLogRoute
  '/plant/$id': typeof PlantIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/users/me': typeof ApiUsersMeRoute
  '/api/sensor-readings/history/$plantId': typeof ApiSensorReadingsHistoryPlantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/plants': typeof PlantsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/watering-log': typeof WateringLogRoute
  '/plant/$id': typeof PlantIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/users/me': typeof ApiUsersMeRoute
  '/api/sensor-readings/history/$plantId': typeof ApiSensorReadingsHistoryPlantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/plants': typeof PlantsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/watering-log': typeof WateringLogRoute
  '/plant/$id': typeof PlantIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/users/me': typeof ApiUsersMeRoute
  '/api/sensor-readings/history/$plantId': typeof ApiSensorReadingsHistoryPlantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/leaderboard'
    | '/login'
    | '/plants'
    | '/profile'
    | '/register'
    | '/watering-log'
    | '/plant/$id'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/users/me'
    | '/api/sensor-readings/history/$plantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/leaderboard'
    | '/login'
    | '/plants'
    | '/profile'
    | '/register'
    | '/watering-log'
    | '/plant/$id'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/users/me'
    | '/api/sensor-readings/history/$plantId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/leaderboard'
    | '/login'
    | '/plants'
    | '/profile'
    | '/register'
    | '/watering-log'
    | '/plant/$id'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/users/me'
    | '/api/sensor-readings/history/$plantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  PlantsRoute: typeof PlantsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  WateringLogRoute: typeof WateringLogRoute
  PlantIdRoute: typeof PlantIdRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiUsersMeRoute: typeof ApiUsersMeRoute
  ApiSensorReadingsHistoryPlantIdRoute: typeof ApiSensorReadingsHistoryPlantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants': {
      id: '/plants'
      path: '/plants'
      fullPath: '/plants'
      preLoaderRoute: typeof PlantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watering-log': {
      id: '/watering-log'
      path: '/watering-log'
      fullPath: '/watering-log'
      preLoaderRoute: typeof WateringLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant/$id': {
      id: '/plant/$id'
      path: '/plant/$id'
      fullPath: '/plant/$id'
      preLoaderRoute: typeof PlantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/me': {
      id: '/api/users/me'
      path: '/api/users/me'
      fullPath: '/api/users/me'
      preLoaderRoute: typeof ApiUsersMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sensor-readings/history/$plantId': {
      id: '/api/sensor-readings/history/$plantId'
      path: '/api/sensor-readings/history/$plantId'
      fullPath: '/api/sensor-readings/history/$plantId'
      preLoaderRoute: typeof ApiSensorReadingsHistoryPlantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  PlantsRoute: PlantsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  WateringLogRoute: WateringLogRoute,
  PlantIdRoute: PlantIdRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiUsersMeRoute: ApiUsersMeRoute,
  ApiSensorReadingsHistoryPlantIdRoute: ApiSensorReadingsHistoryPlantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
